// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: protobuf/traffic_payload/message.proto

package trafficpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_protobuf_traffic_payload_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_traffic_payload_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_protobuf_traffic_payload_message_proto_rawDescGZIP(), []int{0}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type HttpResponseParam struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Method          string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	RequestHeaders  map[string]*StringList `protobuf:"bytes,4,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestPayload  string                 `protobuf:"bytes,5,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	ApiCollectionId int32                  `protobuf:"varint,6,opt,name=api_collection_id,json=apiCollectionId,proto3" json:"api_collection_id,omitempty"`
	StatusCode      int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ResponseHeaders map[string]*StringList `protobuf:"bytes,9,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponsePayload string                 `protobuf:"bytes,10,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	Time            int32                  `protobuf:"varint,11,opt,name=time,proto3" json:"time,omitempty"`
	AktoAccountId   string                 `protobuf:"bytes,12,opt,name=akto_account_id,json=aktoAccountId,proto3" json:"akto_account_id,omitempty"`
	Ip              string                 `protobuf:"bytes,13,opt,name=ip,proto3" json:"ip,omitempty"`
	DestIp          string                 `protobuf:"bytes,14,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	Direction       string                 `protobuf:"bytes,15,opt,name=direction,proto3" json:"direction,omitempty"`
	IsPending       bool                   `protobuf:"varint,16,opt,name=is_pending,json=isPending,proto3" json:"is_pending,omitempty"`
	Source          string                 `protobuf:"bytes,17,opt,name=source,proto3" json:"source,omitempty"`
	AktoVxlanId     string                 `protobuf:"bytes,18,opt,name=akto_vxlan_id,json=aktoVxlanId,proto3" json:"akto_vxlan_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpResponseParam) Reset() {
	*x = HttpResponseParam{}
	mi := &file_protobuf_traffic_payload_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponseParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseParam) ProtoMessage() {}

func (x *HttpResponseParam) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_traffic_payload_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseParam.ProtoReflect.Descriptor instead.
func (*HttpResponseParam) Descriptor() ([]byte, []int) {
	return file_protobuf_traffic_payload_message_proto_rawDescGZIP(), []int{1}
}

func (x *HttpResponseParam) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpResponseParam) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpResponseParam) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HttpResponseParam) GetRequestHeaders() map[string]*StringList {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *HttpResponseParam) GetRequestPayload() string {
	if x != nil {
		return x.RequestPayload
	}
	return ""
}

func (x *HttpResponseParam) GetApiCollectionId() int32 {
	if x != nil {
		return x.ApiCollectionId
	}
	return 0
}

func (x *HttpResponseParam) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponseParam) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HttpResponseParam) GetResponseHeaders() map[string]*StringList {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *HttpResponseParam) GetResponsePayload() string {
	if x != nil {
		return x.ResponsePayload
	}
	return ""
}

func (x *HttpResponseParam) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *HttpResponseParam) GetAktoAccountId() string {
	if x != nil {
		return x.AktoAccountId
	}
	return ""
}

func (x *HttpResponseParam) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HttpResponseParam) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *HttpResponseParam) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *HttpResponseParam) GetIsPending() bool {
	if x != nil {
		return x.IsPending
	}
	return false
}

func (x *HttpResponseParam) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HttpResponseParam) GetAktoVxlanId() string {
	if x != nil {
		return x.AktoVxlanId
	}
	return ""
}

var File_protobuf_traffic_payload_message_proto protoreflect.FileDescriptor

const file_protobuf_traffic_payload_message_proto_rawDesc = "" +
	"\n" +
	"&protobuf/traffic_payload/message.proto\x12/threat_detection.message.http_response_param.v1\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xf1\a\n" +
	"\x11HttpResponseParam\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x7f\n" +
	"\x0frequest_headers\x18\x04 \x03(\v2V.threat_detection.message.http_response_param.v1.HttpResponseParam.RequestHeadersEntryR\x0erequestHeaders\x12'\n" +
	"\x0frequest_payload\x18\x05 \x01(\tR\x0erequestPayload\x12*\n" +
	"\x11api_collection_id\x18\x06 \x01(\x05R\x0fapiCollectionId\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x82\x01\n" +
	"\x10response_headers\x18\t \x03(\v2W.threat_detection.message.http_response_param.v1.HttpResponseParam.ResponseHeadersEntryR\x0fresponseHeaders\x12)\n" +
	"\x10response_payload\x18\n" +
	" \x01(\tR\x0fresponsePayload\x12\x12\n" +
	"\x04time\x18\v \x01(\x05R\x04time\x12&\n" +
	"\x0fakto_account_id\x18\f \x01(\tR\raktoAccountId\x12\x0e\n" +
	"\x02ip\x18\r \x01(\tR\x02ip\x12\x17\n" +
	"\adest_ip\x18\x0e \x01(\tR\x06destIp\x12\x1c\n" +
	"\tdirection\x18\x0f \x01(\tR\tdirection\x12\x1d\n" +
	"\n" +
	"is_pending\x18\x10 \x01(\bR\tisPending\x12\x16\n" +
	"\x06source\x18\x11 \x01(\tR\x06source\x12\"\n" +
	"\rakto_vxlan_id\x18\x12 \x01(\tR\vaktoVxlanId\x1a~\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12Q\n" +
	"\x05value\x18\x02 \x01(\v2;.threat_detection.message.http_response_param.v1.StringListR\x05value:\x028\x01\x1a\x7f\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12Q\n" +
	"\x05value\x18\x02 \x01(\v2;.threat_detection.message.http_response_param.v1.StringListR\x05value:\x028\x01B<B\x16HttpResponseParamProtoZ\"protobuf/traffic_payload;trafficpbb\x06proto3"

var (
	file_protobuf_traffic_payload_message_proto_rawDescOnce sync.Once
	file_protobuf_traffic_payload_message_proto_rawDescData []byte
)

func file_protobuf_traffic_payload_message_proto_rawDescGZIP() []byte {
	file_protobuf_traffic_payload_message_proto_rawDescOnce.Do(func() {
		file_protobuf_traffic_payload_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_traffic_payload_message_proto_rawDesc), len(file_protobuf_traffic_payload_message_proto_rawDesc)))
	})
	return file_protobuf_traffic_payload_message_proto_rawDescData
}

var file_protobuf_traffic_payload_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_traffic_payload_message_proto_goTypes = []any{
	(*StringList)(nil),        // 0: threat_detection.message.http_response_param.v1.StringList
	(*HttpResponseParam)(nil), // 1: threat_detection.message.http_response_param.v1.HttpResponseParam
	nil,                       // 2: threat_detection.message.http_response_param.v1.HttpResponseParam.RequestHeadersEntry
	nil,                       // 3: threat_detection.message.http_response_param.v1.HttpResponseParam.ResponseHeadersEntry
}
var file_protobuf_traffic_payload_message_proto_depIdxs = []int32{
	2, // 0: threat_detection.message.http_response_param.v1.HttpResponseParam.request_headers:type_name -> threat_detection.message.http_response_param.v1.HttpResponseParam.RequestHeadersEntry
	3, // 1: threat_detection.message.http_response_param.v1.HttpResponseParam.response_headers:type_name -> threat_detection.message.http_response_param.v1.HttpResponseParam.ResponseHeadersEntry
	0, // 2: threat_detection.message.http_response_param.v1.HttpResponseParam.RequestHeadersEntry.value:type_name -> threat_detection.message.http_response_param.v1.StringList
	0, // 3: threat_detection.message.http_response_param.v1.HttpResponseParam.ResponseHeadersEntry.value:type_name -> threat_detection.message.http_response_param.v1.StringList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_traffic_payload_message_proto_init() }
func file_protobuf_traffic_payload_message_proto_init() {
	if File_protobuf_traffic_payload_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_traffic_payload_message_proto_rawDesc), len(file_protobuf_traffic_payload_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_traffic_payload_message_proto_goTypes,
		DependencyIndexes: file_protobuf_traffic_payload_message_proto_depIdxs,
		MessageInfos:      file_protobuf_traffic_payload_message_proto_msgTypes,
	}.Build()
	File_protobuf_traffic_payload_message_proto = out.File
	file_protobuf_traffic_payload_message_proto_goTypes = nil
	file_protobuf_traffic_payload_message_proto_depIdxs = nil
}
